name: 'PromptPal Action'
description: 'PromptPal Action that can generate typescript and go types from PromptPal schema'
author: 'AnnatarHe'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'blue'

# Define your inputs here.
inputs:
  token:
    description: 'Github Personal Access Token'
    required: false
  command:
    description: 'Command to execute'
    required: true
    default: 'pp --help'

# Define your outputs here.
# outputs:
#   time:
#     description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
